default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
      trusted_users:
        127.0.0.1:
          - 1294a1db0c61464ca12f5acc2519197d
        ::1:
          - 1294a1db0c61464ca12f5acc2519197d
      allow_bypass_login: true
    - type: homeassistant

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.pp_reader: debug
